apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nodeport-echo","namespace":"ebpf-nodeport-test"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"name":"http","nodePort":30080,"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"nodeport-echo"},"type":"NodePort"}}
  creationTimestamp: "2026-05-11T15:34:14Z"
  name: nodeport-echo
  namespace: ebpf-nodeport-test
  resourceVersion: "6818177"
  uid: 6fe9c728-d315-42d6-9e0d-a1dd643b4ca9
spec:
  clusterIP: 10.105.26.51
  clusterIPs:
  - 10.105.26.51
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodeport-echo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
