apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nodeport-echo","namespace":"ebpf-nodeport-test"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"name":"http","nodePort":30080,"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"nodeport-echo"},"type":"NodePort"}}
  creationTimestamp: "2026-05-23T08:43:39Z"
  name: nodeport-echo
  namespace: ebpf-nodeport-test
  resourceVersion: "9508726"
  uid: 97085033-f35c-4620-a539-9f0db995ec21
spec:
  clusterIP: 10.97.140.22
  clusterIPs:
  - 10.97.140.22
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodeport-echo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
